import LegalPageLayout, { LegalSection, DefinitionBlock, BulletList } from "./LegalPageLayout";

const SECTIONS = [
  { id: "acceptance", label: "Acceptance of Terms" },
  { id: "definitions", label: "Definitions" },
  { id: "account", label: "Account Registration" },
  { id: "ip-rights", label: "Intellectual Property" },
  { id: "acceptable-use", label: "Acceptable Use" },
  { id: "content-services", label: "Content & Services" },
  { id: "payment", label: "Payment Terms" },
  { id: "privacy", label: "Privacy & Data" },
  { id: "liability", label: "Limitation of Liability" },
  { id: "indemnification", label: "Indemnification" },
  { id: "termination", label: "Termination" },
  { id: "governing-law", label: "Governing Law" },
  { id: "changes", label: "Changes to Terms" },
  { id: "contact", label: "Contact Us" },
];

export default function TermsAndConditions() {
  return (
    <LegalPageLayout
      title="Terms and Conditions"
      lastUpdated="July 15, 2026"
      sections={SECTIONS}
    >
      <LegalSection id="acceptance" title="Acceptance of Terms">
        <p>
          Welcome to Prysmors. These Terms and Conditions ("Terms") govern your access to and
          use of the Prysmors enterprise decision intelligence platform, including our website,
          APIs, dashboards, and all related services (collectively, the "Service"). By accessing
          or using the Service, you agree to be bound by these Terms.
        </p>
        <p>
          If you are using the Service on behalf of an organization, you represent and warrant
          that you have the authority to bind that organization to these Terms, and "you" refers
          to both you individually and the organization. If you do not agree to these Terms, you
          must not access or use the Service.
        </p>
      </LegalSection>

      <LegalSection id="definitions" title="Definitions">
        <DefinitionBlock
          terms={[
            ["Service", "The Prysmors enterprise platform, including all associated APIs, dashboards, analytics tools, documentation, and the website at prysmors.com."],
            ["User", "Any individual or entity that accesses or uses the Service."],
            ["Account", "A registered account created to access specific features of the Service."],
            ["Content", "All data, text, files, information, analytics outputs, reports, and materials uploaded to, generated by, or transmitted through the Service."],
            ["Enterprise Data", "Business or organizational data processed through the Service by authorized Users."],
            ["Subscription", "A paid plan granting access to specific Service features and usage limits."],
            ["API", "Application Programming Interface provided as part of the Service for programmatic access."],
          ]}
        />
      </LegalSection>

      <LegalSection id="account" title="Account Registration and Security">
        <p>
          To access certain features, you must create an Account. You agree to provide accurate,
          current, and complete information during registration and to update it as necessary.
          You are responsible for:
        </p>
        <BulletList
          items={[
            "Safeguarding your Account credentials and not sharing them with unauthorized parties.",
            "All activities that occur under your Account, including those performed by users you authorize.",
            "Notifying us immediately if you suspect unauthorized access or a security breach.",
            "Ensuring that your authorized users comply with these Terms.",
          ]}
        />
        <p>
          We reserve the right to suspend or terminate Accounts that we reasonably believe have
          been compromised or are being used in violation of these Terms.
        </p>
      </LegalSection>

      <LegalSection id="ip-rights" title="Intellectual Property Rights">
        <p>
          The Service and its original content, features, functionality, design, documentation,
          and underlying technology are owned by Prysmors, Inc. and are protected by United
          States and international copyright, trademark, patent, trade secret, and other
          intellectual property laws.
        </p>
        <p>
          Subject to your Subscription and compliance with these Terms, we grant you a limited,
          non-exclusive, non-transferable, revocable license to access and use the Service for
          your internal business purposes. This license does not include the right to:
        </p>
        <BulletList
          items={[
            "Copy, modify, distribute, sell, or lease any part of the Service or its technology.",
            "Reverse engineer, decompile, or attempt to extract the source code of the Service.",
            "Use the Service to build a competing product or service.",
            "Remove, alter, or obscure any proprietary notices or labels on the Service.",
            "Use our trademarks, logos, or branding without prior written consent.",
          ]}
        />
        <p>
          You retain all rights to Enterprise Data you upload to the Service. By using the
          Service, you grant us a limited, non-exclusive license to process your Enterprise
          Data solely for the purpose of providing the Service to you.
        </p>
      </LegalSection>

      <LegalSection id="acceptable-use" title="Acceptable Use Policy">
        <p>You agree not to use the Service to:</p>
        <BulletList
          items={[
            "Violate any applicable local, state, national, or international law or regulation.",
            "Infringe upon or violate the intellectual property rights or privacy of others.",
            "Upload or transmit malicious code, viruses, worms, Trojan horses, or other harmful technology.",
            "Attempt to gain unauthorized access to other accounts, computer systems, or networks connected to the Service.",
            "Interfere with or disrupt the Service, servers, or networks, including through denial-of-service attacks.",
            "Use the Service to send unsolicited communications, spam, or phishing attempts.",
            "Process or transmit data that is illegal, harmful, threatening, abusive, or otherwise objectionable.",
            "Exceed your authorized usage limits or circumvent any rate limiting or access controls.",
            "Resell, sublicense, or redistribute the Service or any outputs generated by the Service without authorization.",
          ]}
        />
        <p>
          We reserve the right to investigate and take appropriate action against anyone who
          violates this policy, including suspension or termination of access without prior notice.
        </p>
      </LegalSection>

      <LegalSection id="content-services" title="Content, Services, and Availability">
        <p>
          The Service is provided on an "as available" and "as is" basis. We make no warranties
          that the Service will be uninterrupted, timely, secure, or error-free. We do not
          guarantee the accuracy, completeness, or reliability of any analytics, predictions,
          recommendations, or outputs generated by the Service.
        </p>
        <p>
          AI-generated outputs, including predictive analytics, risk assessments, and decision
          recommendations, are provided for informational purposes and should not be the sole
          basis for critical business decisions. You are responsible for reviewing and validating
          all outputs before acting on them.
        </p>
        <p>
          We may temporarily suspend or limit access to the Service for maintenance, updates,
          or security reasons. We will use commercially reasonable efforts to provide advance
          notice of planned downtime.
        </p>
      </LegalSection>

      <LegalSection id="payment" title="Payment Terms and Subscriptions">
        <p>
          Certain features of the Service require a paid Subscription. By selecting a paid plan,
          you agree to the following terms:
        </p>
        <BulletList
          items={[
            "All fees are stated in U.S. dollars and are non-refundable unless otherwise specified.",
            "Subscriptions renew automatically at the end of each billing cycle unless canceled.",
            "You may cancel your Subscription at any time; cancellation takes effect at the end of the current billing period.",
            "We reserve the right to modify pricing with at least 30 days' prior written notice.",
            "Failure to pay may result in suspension or termination of your Account and access to the Service.",
            "Taxes are your responsibility unless we are legally required to collect them.",
          ]}
        />
      </LegalSection>

      <LegalSection id="privacy" title="Privacy and Data Protection">
        <p>
          Our collection and use of personal information is governed by our Privacy Policy. By
          using the Service, you consent to the collection, use, and disclosure of information
          as described in our Privacy Policy.
        </p>
        <p>
          For enterprise customers processing personal data of EU/EEA residents, we offer a
          Data Processing Agreement (DPA) upon request. We maintain SOC 2-aligned controls,
          implement encryption in transit and at rest, and undergo regular third-party security
          audits to protect your data.
        </p>
      </LegalSection>

      <LegalSection id="liability" title="Limitation of Liability">
        <p>
          To the maximum extent permitted by applicable law, in no event shall Prysmors, Inc.,
          its directors, employees, partners, agents, suppliers, or affiliates be liable for:
        </p>
        <BulletList
          items={[
            "Any indirect, incidental, special, consequential, or punitive damages resulting from your use of the Service.",
            "Any loss of profits, data, goodwill, or other intangible losses.",
            "Any damages resulting from errors, inaccuracies, or omissions in the Service or its outputs.",
            "Any unauthorized access to or alteration of your data or transmissions.",
            "Any interruption or cessation of the Service.",
          ]}
        />
        <p>
          Our total aggregate liability to you for all claims arising out of or relating to the
          use of or inability to use the Service shall not exceed the greater of (a) the amount
          you paid to us in the twelve (12) months preceding the claim, or (b) one hundred
          U.S. dollars ($100).
        </p>
      </LegalSection>

      <LegalSection id="indemnification" title="Indemnification">
        <p>
          You agree to defend, indemnify, and hold harmless Prysmors, Inc. and its officers,
          directors, employees, contractors, agents, licensors, and suppliers from and against
          any claims, actions, demands, liabilities, and settlements, including reasonable legal
          and accounting fees, resulting from or alleged to result from:
        </p>
        <BulletList
          items={[
            "Your use of the Service in violation of these Terms.",
            "Your violation of any applicable law or regulation.",
            "Your Enterprise Data or Content that you upload, process, or transmit through the Service.",
            "Your infringement or misappropriation of any third-party right, including intellectual property or privacy rights.",
          ]}
        />
      </LegalSection>

      <LegalSection id="termination" title="Termination">
        <p>
          We may terminate or suspend your Account and access to the Service immediately, without
          prior notice or liability, for any reason, including without limitation if you breach
          these Terms.
        </p>
        <p>
          Upon termination, your right to use the Service will immediately cease. You may
          request export of your Enterprise Data within thirty (30) days of termination, after
          which we may delete your data in accordance with our data retention policies.
        </p>
        <p>
          All provisions of these Terms which by their nature should survive termination shall
          survive, including ownership provisions, warranty disclaimers, indemnity, and
          limitations of liability.
        </p>
      </LegalSection>

      <LegalSection id="governing-law" title="Governing Law and Dispute Resolution">
        <p>
          These Terms shall be governed by and construed in accordance with the laws of the
          State of Delaware, United States, without regard to its conflict of law provisions.
        </p>
        <p>
          Any dispute arising from or relating to these Terms or the Service shall first be
          attempted to be resolved through good-faith negotiation. If the dispute cannot be
          resolved within thirty (30) days, either party may pursue binding arbitration under
          the rules of the American Arbitration Association. The arbitration shall be conducted
          in English in Wilmington, Delaware.
        </p>
      </LegalSection>

      <LegalSection id="changes" title="Changes to These Terms">
        <p>
          We reserve the right to modify or replace these Terms at any time at our sole
          discretion. If a revision is material, we will provide at least thirty (30) days'
          notice prior to any new terms taking effect, which may be provided via email, in-app
          notification, or posting on our website.
        </p>
        <p>
          By continuing to access or use our Service after those revisions become effective,
          you agree to be bound by the revised Terms. If you do not agree to the new Terms,
          you are no longer authorized to use the Service.
        </p>
      </LegalSection>

      <LegalSection id="contact" title="Contact Us">
        <p>
          If you have any questions about these Terms and Conditions, please contact us:
        </p>
        <div className="mt-4 rounded-xl border border-[var(--color-border-soft)] bg-[var(--color-surface)]/40 p-5 space-y-2">
          <p className="text-[var(--color-text)] font-semibold">Prysmors, Inc.</p>
          <p>Legal Team</p>
          <p>
            Email:{" "}
            <a href="mailto:legal@prysmors.com" className="text-[var(--color-mint)] hover:underline">
              legal@prysmors.com
            </a>
          </p>
          <p>
            Web:{" "}
            <a href="/contact" className="text-[var(--color-mint)] hover:underline">
              Contact Page
            </a>
          </p>
        </div>
      </LegalSection>
    </LegalPageLayout>
  );
}
